get http://localhost:5006/appuser/register
Content-Type: application/json

{
    "nom" : "Lebon",
    "prenom" : "maxime",
    "pseudo" : "marcel",
    "email": "lebon.maxime.m@gmail.com",
    "password": "test"
}